import fs from 'node:fs/promises';

const owner = '<strong>José Antonio Cuenca Gómez</strong>, NIF <strong>44393436D</strong>, con domicilio en <strong>Calle Ibáñez Ibero, 11, 3.º A, 02005 Albacete, España</strong>.';
const email = '<a href="mailto:info@joseantoniocuenca.es">info@joseantoniocuenca.es</a> · Teléfono: <a href="tel:+34615559577">615 55 95 77</a>';
const pages = [
  { file: 'aviso-legal.html', title: 'Aviso legal', summary: 'Identificación del titular y condiciones de uso de esta web profesional.', sections: [
    ['1. Titular de la web', `<p>El titular de <a href="https://joseantoniocuenca.es/">joseantoniocuenca.es</a> es ${owner}</p><p>Contacto: ${email}.</p><p>Estos datos se facilitan de conformidad con el artículo 10 de la Ley 34/2002, de servicios de la sociedad de la información y de comercio electrónico.</p>`],
    ['2. Objeto y destinatarios', '<p>Esta web presenta la actividad de gestión comercial de José Antonio Cuenca en sistemas de descanso premium y las marcas representadas. Está dirigida a profesionales del sector y ofrece un canal para consultas comerciales.</p><p>No es una tienda online, no permite contratar ni pagar productos y no realiza venta directa al consumidor. La información publicada no constituye por sí sola una oferta contractual vinculante.</p>'],
    ['3. Uso de la web', '<p>El acceso es gratuito, sin perjuicio del coste de conexión de cada usuario. Quien utilice la web debe hacerlo de forma lícita, respetuosa y conforme a estas condiciones. No se permite introducir código malicioso, intentar acceder a zonas no autorizadas, suplantar identidades, remitir comunicaciones abusivas ni perjudicar el funcionamiento del servicio.</p><p>Los datos enviados mediante el formulario deben ser veraces y corresponder a quien realiza la consulta o a una persona que le haya autorizado. No incluyas datos especialmente sensibles ni información de terceros innecesaria.</p>'],
    ['4. Propiedad intelectual e industrial', '<p>El diseño, los textos y los demás elementos de esta web están protegidos por la normativa aplicable. Las marcas, logotipos, fotografías y materiales de fabricantes pertenecen a sus respectivos titulares. Su presencia en la web no transmite derechos al visitante ni atribuye su propiedad a José Antonio Cuenca.</p><p>Fuera de los usos permitidos por la ley, la reproducción, distribución, transformación o explotación de contenidos requiere autorización del titular de los derechos. Las fuentes tipográficas y librerías utilizadas mantienen sus propias licencias.</p>'],
    ['5. Información, disponibilidad y enlaces', '<p>El titular procura que la información sea correcta y que la web funcione adecuadamente, pero puede actualizar sus contenidos y efectuar tareas de mantenimiento. La disponibilidad, características y condiciones comerciales de productos deben confirmarse directamente antes de adoptar decisiones de negocio.</p><p>Los enlaces a páginas externas se ofrecen como información. Su contenido y sus políticas dependen de sus respectivos titulares. Ninguna disposición de este aviso excluye responsabilidades que no puedan limitarse conforme a la ley.</p>'],
    ['6. Datos personales y cookies', '<p>El tratamiento de datos se explica en la <a href="/privacidad.html">Política de privacidad</a>. El uso de cookies y tecnologías similares se explica en la <a href="/cookies.html">Política de cookies</a>.</p>'],
    ['7. Legislación y resolución de controversias', `<p>Se aplica la legislación española y la normativa de la Unión Europea que resulte pertinente. Para cualquier cuestión puedes contactar mediante ${email}. Si no se alcanza una solución, serán competentes los juzgados y tribunales que determine la normativa aplicable, respetando los fueros imperativos que correspondan.</p>`]
  ] },
  { file: 'privacidad.html', title: 'Política de privacidad', summary: 'Cómo se utilizan los datos de tus consultas y cómo ejercer tus derechos.', sections: [
    ['1. Responsable del tratamiento', `<p>El responsable es ${owner}</p><p>Para cuestiones de privacidad y ejercicio de derechos: ${email}.</p>`],
    ['2. Datos que se recogen', '<p>El formulario solicita nombre, email, empresa opcional y mensaje. Los campos marcados con asterisco son necesarios para atender la consulta. No se solicitan datos de pago ni categorías especiales de datos personales.</p><p>El servidor puede tratar datos técnicos de conexión, como dirección IP, fecha y registros de acceso, para operar y proteger el servicio. La protección del formulario emplea un identificador de IP seudonimizado mediante HMAC y marcas de tiempo; no guarda el contenido de las consultas en la web.</p><p>Si contactas por email, se tratarán la dirección del remitente y los datos que decidas incluir. Evita información sensible y datos de terceros que no sean necesarios.</p>'],
    ['3. Finalidades y bases jurídicas', '<ul><li><strong>Responder consultas:</strong> atender solicitudes profesionales y comunicaciones iniciadas por ti. El formulario pide tu consentimiento para este fin, conforme al artículo 6.1.a del RGPD. Puedes retirarlo sin afectar a la licitud del tratamiento anterior.</li><li><strong>Gestiones comerciales solicitadas:</strong> cuando una consulta requiera medidas precontractuales o una relación contractual, el tratamiento necesario se basa en el artículo 6.1.b del RGPD, cuando resulte aplicable.</li><li><strong>Seguridad del servicio:</strong> prevenir spam, abuso y accesos indebidos, sobre la base del interés legítimo de proteger la web y sus usuarios, artículo 6.1.f del RGPD, con medidas proporcionadas.</li><li><strong>Obligaciones legales:</strong> atender las obligaciones normativas y requerimientos válidos que correspondan, artículo 6.1.c del RGPD.</li></ul><p>El formulario no te suscribe a newsletters ni autoriza campañas publicitarias. No se toman decisiones automatizadas con efectos jurídicos ni se elaboran perfiles comerciales desde esta web.</p>'],
    ['4. Conservación: máximo tres meses', '<p><strong>Las consultas y su contenido se conservarán como máximo tres meses desde su recepción.</strong> Este plazo comprende los mensajes recibidos en el buzón, sus adjuntos y las copias de trabajo, no solo el formulario.</p><p>Si surge una relación comercial, los datos estrictamente necesarios para esa relación se tratarán separadamente durante el tiempo necesario para gestionarla y cumplir sus obligaciones legales. Esto no autoriza a mantener indefinidamente la consulta original.</p><p>Cuando exista una obligación legal o una reclamación que impida suprimir determinados datos, se conservarán únicamente los necesarios, con acceso restringido o bloqueo cuando proceda, durante el plazo exigible. Los registros técnicos de seguridad se limitarán al tiempo necesario para investigar incidencias y operar el servicio.</p><p>El estado antiabuso del formulario utiliza una ventana de diez minutos; las entradas vencidas se depuran en la siguiente solicitud de envío. No contiene el nombre, email ni mensaje.</p>'],
    ['5. Destinatarios y proveedores', '<p>La consulta se dirige a José Antonio Cuenca. Los proveedores necesarios de alojamiento, mantenimiento y correo, incluido IONOS para el envío SMTP, pueden acceder a los datos para prestar sus servicios como encargados del tratamiento, conforme a sus contratos y a la normativa aplicable.</p><p>No se venden los datos ni se ceden a fabricantes para publicidad desde este formulario. Se podrán comunicar datos cuando exista una obligación legal o un requerimiento válido de una autoridad competente.</p><p>El envío utiliza SMTP con cifrado TLS. Los datos no se muestran en páginas públicas. El correo electrónico no debe utilizarse para remitir información especialmente sensible.</p>'],
    ['6. Transferencias internacionales', `<p>Los servicios de terceros se utilizarán con las garantías exigidas por el RGPD. Si un proveedor necesitara tratar datos fuera del Espacio Económico Europeo, deberá existir una decisión de adecuación u otra garantía válida prevista en los artículos 44 y siguientes del RGPD, junto con las medidas complementarias que procedan. Puedes solicitar información sobre los proveedores y garantías aplicables mediante ${email}.</p>`],
    ['7. Tus derechos', `<p>Puedes solicitar acceso, rectificación, supresión, oposición, limitación del tratamiento y portabilidad cuando proceda, así como retirar el consentimiento, escribiendo a ${email} o al domicilio del responsable. Indica el derecho que deseas ejercer y la información necesaria para localizar tu solicitud. Solo se pedirá información adicional para verificar tu identidad si resulta necesario y proporcionado.</p><p>Se responderá, con carácter general, en el plazo de un mes; las ampliaciones legalmente previstas se comunicarán con su motivo. Si consideras que el tratamiento no cumple la normativa, puedes reclamar ante la <a href="https://www.aepd.es/" target="_blank" rel="noopener noreferrer">Agencia Española de Protección de Datos<span class="sr-only"> (abre nueva pestaña)</span></a>.</p>`],
    ['8. Actualización de esta política', '<p>Esta política se adapta al funcionamiento actual del sitio. Si cambian las finalidades, los servicios o las tecnologías utilizadas, se actualizará la información y se solicitará consentimiento adicional cuando sea necesario.</p>']
  ] },
  { file: 'cookies.html', title: 'Política de cookies', summary: 'Una web sin analítica, publicidad ni cookies instaladas por la aplicación actual.', sections: [
    ['1. Titular y contacto', `<p>Esta política corresponde a la web de ${owner}</p><p>Contacto: ${email}.</p>`],
    ['2. Qué son las cookies', '<p>Las cookies son pequeños archivos que una web puede guardar en tu dispositivo. Otras tecnologías, como el almacenamiento local, pueden cumplir funciones similares. Pueden servir para funciones técnicas, preferencias, medición o publicidad; las tecnologías no necesarias requieren consentimiento previo cuando la normativa lo exige.</p>'],
    ['3. Tecnologías de esta web', '<p><strong>La implementación actual no instala cookies ni utiliza almacenamiento local o de sesión del navegador.</strong> No integra herramientas de analítica, píxeles publicitarios ni seguimiento de visitantes.</p><ul><li>Las fuentes, imágenes y vídeos se sirven desde el propio sitio.</li><li>Los vídeos no son reproductores de YouTube, Vimeo ni otros servicios externos, y solo cargan el archivo MP4 después de tu interacción.</li><li>El formulario obtiene un token temporal de seguridad conservado en memoria mientras está abierto. No crea una cookie ni una sesión de navegador persistente.</li><li>Los registros del servidor y el límite antiabuso no son cookies. Su tratamiento se describe en la <a href="/privacidad.html">Política de privacidad</a>.</li></ul><p>No existe una lista de cookies con nombres o duraciones porque la aplicación no crea ninguna. Por este motivo, no se muestra un banner de aceptación ni un panel de preferencias de cookies.</p>'],
    ['4. Enlaces externos', '<p>Al abrir enlaces de fabricantes, del diseñador o de otros sitios, accedes a servicios que aplican sus propias políticas. Sus posibles cookies no se instalan mediante esta web por el mero hecho de mostrar un enlace.</p>'],
    ['5. Control desde tu navegador', '<p>Puedes consultar, bloquear o borrar cookies desde la configuración de privacidad de tu navegador. Las opciones dependen del navegador y dispositivo utilizados. El bloqueo de cookies no debería impedir el funcionamiento de esta implementación, que no depende de ellas.</p>'],
    ['6. Cambios futuros', '<p>Si se incorporan analítica, publicidad, reproductores externos u otras tecnologías que lo requieran, esta política se actualizará. Las tecnologías no necesarias no se activarán hasta obtener el consentimiento válido del usuario; la opción de rechazarlas deberá ser accesible.</p>']
  ] }
];

export async function generateLegalPages(site = process.env.SITE_URL || 'https://joseantoniocuenca.es') {
  for (const page of pages) {
    const url = new URL(page.file, new URL('/', site)).href;
    const html = `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${page.title} | José Antonio Cuenca</title><meta name="description" content="${page.summary}"><meta name="robots" content="noindex, nofollow"><meta name="theme-color" content="#202521"><link rel="canonical" href="${url}"><link rel="icon" href="/favicon.ico" sizes="any"><link rel="icon" href="/assets/favicon-jc.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="/assets/apple-touch-icon.png"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/legal.css"></head>
<body class="legal-page"><a class="skip-link" href="#contenido">Saltar al contenido</a><header class="legal-header wrap"><a class="legal-brand" href="/">José Antonio Cuenca<span aria-hidden="true">.</span></a><a class="legal-back" href="/">Volver a la web <span aria-hidden="true">↗</span></a></header>
<main class="legal-main wrap" id="contenido"><p class="eyebrow">INFORMACIÓN Y TRANSPARENCIA</p><h1>${page.title}</h1><p class="legal-intro">${page.summary}</p><p class="legal-updated">Última actualización: 6 de octubre de 2026.</p><nav class="legal-nav" aria-label="Documentos legales"><a href="/aviso-legal.html" ${page.file === 'aviso-legal.html' ? 'aria-current="page"' : ''}>Aviso legal</a><a href="/privacidad.html" ${page.file === 'privacidad.html' ? 'aria-current="page"' : ''}>Privacidad</a><a href="/cookies.html" ${page.file === 'cookies.html' ? 'aria-current="page"' : ''}>Cookies</a></nav><article class="legal-content">${page.sections.map(([heading, text]) => `<section><h2>${heading}</h2>${text}</section>`).join('')}</article></main>
<footer class="legal-footer wrap"><span>© 2026 José Antonio Cuenca Gómez.</span><span>Diseño: <a href="https://roblesmagan.com/">Juan Carlos Robles Magán</a> y <a href="https://grupocomunicacion360.com/">Grupo Comunicación 360º</a></span></footer></body></html>`;
    await fs.writeFile(page.file, html.replace('noindex, nofollow', 'noindex, follow'));
  }
}
if (process.argv[1]?.endsWith('legal-pages.mjs')) await generateLegalPages();
